### ISSUE TITLE
Usage with docker container?

### ISSUE THREAD

**Issue by sebascha** [L480/cloudflare-dyndns#22]
This may be a stupid question but how would update url with the local container look like?

**Comment by bulburDE** [comment]
It depends how you have configured your docker container, but here is an example that may help.
I have created the container using the following docker-compose.yml:

```
version: '3.7'

services:
    app:
        container_name: cloudflare-dyndns
        ports:
            - 8504:80
        image: ghcr.io/l480/cloudflare-dyndns:latest
```

The resulting update-url is: `http://<server host name or ip address>:8504?token=<pass>&record=www&zone=example.de&ipv4=<ipaddr>&ipv6=<ip6addr>`

You have to change adapt `<server host name or ip address>` to your server. The other placeholders are filled in by fritz.
